# Generated by Django 2.2.15 on 2020-08-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'M1'), (2, 'M2')])),
                ('item_type', models.IntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')])),
                ('field1', models.TextField()),
                ('field2', models.TextField()),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.Conf')),
            ],
        ),
    ]
